export const REGISTER_USER="REGISTER_USER";
export const REGISTER_USER_UP="REGISTER_USER_UP";
export const LOGIN_USER="LOGIN_USER";
export const lOGIN_USER_UP="lOGIN_USER_UP";
export const DELETE_USER="DELETE_USER";
export const DELETE_USER_UP="DELETE_USER_UP"